--- 
abstract: Use Form::Processor with Catalyst
author: 
  - Bill Moseley
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Plugin-Form-Processor
no_index: 
  directory: 
    - example
    - inc
    - t
recommends: 
  Catalyst::Plugin::I18N: 0.05
  Catalyst::Plugin::Static::Simple: 0.14
  Catalyst::Plugin::Unicode::Encoding: 0.1
  Template: 2.19
requires: 
  Catalyst: 5.50
  Form::Processor: 0.11
  HTML::FillInForm: 0
  UNIVERSAL::require: 0
  perl: 5.8.1
version: 0.05
