# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Form-Processor
version:      0.01
version_from: lib/Catalyst/Plugin/Form/Processor.pm
installdirs:  site
requires:
    Catalyst:                      5.5
    Form::Processor:               0.09
    HTML::FillInForm:              0
    UNIVERSAL::require:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
